--
-- Table "AQ$_SUPPLIER_PROCESS_QUEUE_X"
--
CREATE TABLE "XX_TANGO"."AQ$_SUPPLIER_PROCESS_QUEUE_X" 
   (	"INSTANCE" NUMBER NOT NULL ENABLE, 
	"SHARD_ID" NUMBER NOT NULL ENABLE, 
	"PRIORITY" NUMBER NOT NULL ENABLE, 
	"SUBSHARD_ID" NUMBER NOT NULL ENABLE, 
	"TYPE" NUMBER NOT NULL ENABLE, 
	"MESSAGE_STREAM" BLOB, 
	"BITMAP_STREAM" BLOB, 
	"RECIPIENT_MAP" BLOB, 
	"ENDIAN" NUMBER, 
	 PRIMARY KEY ("INSTANCE", "SHARD_ID", "PRIORITY", "SUBSHARD_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" USAGE QUEUE 
  PARTITION BY RANGE ("INSTANCE") INTERVAL (1) 
 (PARTITION "P1"  VALUES LESS THAN (1) )
/