--
-- Table "AQ$_PM_TEQ_JSON_QUEUE1_L"
--
CREATE TABLE "XX_TANGO"."AQ$_PM_TEQ_JSON_QUEUE1_L" 
   (	"MSGID" RAW(16) DEFAULT 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF', 
	"INCARNATION" NUMBER(*,0) DEFAULT 0, 
	"SEQ_NUM" NUMBER(*,0), 
	"FLAGS" NUMBER(*,0) DEFAULT 4294967295, 
	"DEQUEUE_TIME" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"TRANSACTION_ID" VARCHAR2(30) COLLATE "USING_NLS_COMP" DEFAULT 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF', 
	"DEQUEUE_USER" VARCHAR2(128) COLLATE "USING_NLS_COMP" DEFAULT 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF', 
	"RETRY_COUNT" NUMBER(*,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" USAGE QUEUE 
  PARTITION BY SYSTEM 
 (PARTITION "P0" , 
 PARTITION "P1" , 
 PARTITION "P2" , 
 PARTITION "P3" , 
 PARTITION "P4" )
/