--
-- Table "CUSTOMER_ISHIKA"
--
CREATE TABLE "XX_TANGO"."CUSTOMER_ISHIKA" 
   (	"CUSTOMER_ID" NUMBER(5,0), 
	"CUST_NAME" VARCHAR2(40) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"GRADE" NUMBER(3,0), 
	 CONSTRAINT "PK_CUSTOMER_ID" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/