--
-- Table "DEPARTMENT"
--
CREATE TABLE "XX_TANGO"."DEPARTMENT" 
   (	"DEPT_ID" NUMBER, 
	"DEPT_NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("DEPT_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/