--
-- Table "EBA_UT_CHART_PROJECTS"
--
CREATE TABLE "XX_TANGO"."EBA_UT_CHART_PROJECTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"CREATED" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"UPDATED" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "EBA_UT_CHARTS_PROJ_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/