--
-- Table "EBA_UT_MAP_AIRPORTS"
--
CREATE TABLE "XX_TANGO"."EBA_UT_MAP_AIRPORTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"IATA_CODE" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"AIRPORT_TYPE" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"AIRPORT_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"STATE_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ACTIVATION_DATE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ACTIVATION_DATE_DT" DATE, 
	"ELEVATION" NUMBER, 
	"DIST_CITY_TO_AIRPORT" NUMBER, 
	"LAND_AREA_COVERED" NUMBER, 
	"COMMERCIAL_OPS" NUMBER, 
	"AIR_TAXI_OPS" NUMBER, 
	"GEOMETRY" "MDSYS"."SDO_GEOMETRY" , 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" 
 VARRAY "GEOMETRY"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "GEOMETRY"."SDO_ORDINATES" STORE AS SECUREFILE LOB
/