--
-- Table "EBA_UT_CHART_TASKS"
--
CREATE TABLE "XX_TANGO"."EBA_UT_CHART_TASKS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROJECT" NUMBER, 
	"PARENT_TASK" NUMBER, 
	"TASK_NAME" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"ROW_VERSION_NUMBER" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"ASSIGNED_TO" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"COST" NUMBER, 
	"BUDGET" NUMBER, 
	"CREATED" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	"UPDATED" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "EBA_UT_CHART_TASKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EBA_UT_CHART_TASKS_FK" FOREIGN KEY ("PROJECT")
	  REFERENCES "XX_TANGO"."EBA_UT_CHART_PROJECTS" ("ID") ON DELETE CASCADE ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/