--
-- Table "EBA_DEMO_IG_DEPT"
--
CREATE TABLE "XX_TANGO"."EBA_DEMO_IG_DEPT" 
   (	"DEPTNO" NUMBER, 
	"DNAME" VARCHAR2(60) COLLATE "USING_NLS_COMP", 
	"LOC" VARCHAR2(40) COLLATE "USING_NLS_COMP", 
	"NOTES" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("DEPTNO")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/