--
-- Table "EBA_DEMO_IG_EMP"
--
CREATE TABLE "XX_TANGO"."EBA_DEMO_IG_EMP" 
   (	"EMPNO" NUMBER NOT NULL ENABLE, 
	"ENAME" VARCHAR2(60) COLLATE "USING_NLS_COMP", 
	"JOB" VARCHAR2(9) COLLATE "USING_NLS_COMP", 
	"MGR" NUMBER, 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"ONLEAVE" VARCHAR2(1) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NOTES" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"DEPTNO" NUMBER, 
	"FLEX1" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"FLEX2" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"FLEX3" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"FLEX4" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"RATING" NUMBER, 
	 CONSTRAINT "EBA_DEMO_IG_EMP_RATING_CK" CHECK (RATING between 0 and 9) ENABLE, 
	 CONSTRAINT "EBA_DEMO_IG_EMP_ONLEAVE_CK" CHECK (ONLEAVE in ('Y', 'N')) ENABLE, 
	 PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE, 
	 FOREIGN KEY ("MGR")
	  REFERENCES "XX_TANGO"."EBA_DEMO_IG_EMP" ("EMPNO") ENABLE, 
	 FOREIGN KEY ("DEPTNO")
	  REFERENCES "XX_TANGO"."EBA_DEMO_IG_DEPT" ("DEPTNO") ON DELETE CASCADE ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/