--
-- Table "EBA_UT_DEMO_CARDS"
--
CREATE TABLE "XX_TANGO"."EBA_UT_DEMO_CARDS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TITLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SUBTITLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BODY" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SECONDARY_BODY" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP", 
	"ICON_CLASS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"BADGE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP", 
	"IMAGE_URL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"END_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	 CONSTRAINT "EBA_UT_DEMO_CARDS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/