--
-- Table "EMPLOYEE_TBL"
--
CREATE TABLE "XX_TANGO"."EMPLOYEE_TBL" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"EMAIL_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"
/