--
-- Table "MY_LOG_CB_ERRORS"
--
CREATE TABLE "XX_TANGO"."MY_LOG_CB_ERRORS" 
   (	"MESSAGE" JSON, 
	"WHEN_TIME" TIMESTAMP (6), 
	"MSGID" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"ERROR_MESSAGE" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(100) COLLATE "USING_NLS_COMP" DEFAULT 'ERROR'
   )  DEFAULT COLLATION "USING_NLS_COMP"
/