--
-- Table "SDW$ERR$_CUSTOMER_ISHIKA"
--
CREATE TABLE "XX_TANGO"."SDW$ERR$_CUSTOMER_ISHIKA" 
   (	"ORA_ERR_NUMBER$" NUMBER, 
	"ORA_ERR_MESG$" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"ORA_ERR_ROWID$" UROWID (4000), 
	"ORA_ERR_OPTYP$" VARCHAR2(2) COLLATE "USING_NLS_COMP", 
	"ORA_ERR_TAG$" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"CUSTOMER_ID" VARCHAR2(4000) COLLATE "USING_NLS_COMP", 
	"CUST_NAME" VARCHAR2(32767) COLLATE "USING_NLS_COMP", 
	"CITY" VARCHAR2(32767) COLLATE "USING_NLS_COMP", 
	"GRADE" VARCHAR2(4000) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"
/