--
-- Table "XX_INT_LAYERS_T"
--
CREATE TABLE "XX_TANGO"."XX_INT_LAYERS_T" 
   (	"INT_LAYERS_ID" NUMBER DEFAULT XX_TANGO.XX_INT_LAYERS_S1.nextval, 
	"INT_LAYER_NUM" NUMBER, 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SHORT_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"SOURCE_SYSTEM_ID" NUMBER, 
	"TARGET_SYSTEM_ID" NUMBER, 
	"MIDDLEWARE_ID" NUMBER, 
	"ENABLE_FLAG" BOOLEAN NOT NULL ENABLE, 
	"OBJECT_VERSION_NUMBER" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "XX_INT_LAYERS_PK1" PRIMARY KEY ("INT_LAYERS_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("INT_LAYER_NUM")
  USING INDEX  ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX  ENABLE, 
	 UNIQUE ("SHORT_NAME")
  USING INDEX  ENABLE, 
	 UNIQUE ("DESCRIPTION")
  USING INDEX  ENABLE, 
	 CONSTRAINT "XX_INT_LAYERS_FK1" FOREIGN KEY ("SOURCE_SYSTEM_ID")
	  REFERENCES "XX_TANGO"."XX_SYSTEMS_T" ("SYSTEM_ID") ENABLE, 
	 CONSTRAINT "XX_INT_LAYERS_FK2" FOREIGN KEY ("TARGET_SYSTEM_ID")
	  REFERENCES "XX_TANGO"."XX_SYSTEMS_T" ("SYSTEM_ID") ENABLE, 
	 CONSTRAINT "XX_INT_LAYERS_FK3" FOREIGN KEY ("MIDDLEWARE_ID")
	  REFERENCES "XX_TANGO"."XX_MIDDLEWARES_T" ("MIDDLEWARE_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/