--
-- Table "XX_INT_RUN_T"
--
CREATE TABLE "XX_TANGO"."XX_INT_RUN_T" 
   (	"INT_RUN_ID" NUMBER DEFAULT XX_TANGO.XX_INT_RUN_S1.nextval, 
	"INT_LAYERS_ID" NUMBER, 
	"CREATED_COMPONENT_ID" NUMBER, 
	"RUN_IDENTIFIER" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"MSGID" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"INSTANCE_STATUS" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "XX_INT_RUN_PK1" PRIMARY KEY ("INT_RUN_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "XX_INT_RUN_FK1" FOREIGN KEY ("INT_LAYERS_ID")
	  REFERENCES "XX_TANGO"."XX_INT_LAYERS_T" ("INT_LAYERS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_RUN_FK2" FOREIGN KEY ("CREATED_COMPONENT_ID")
	  REFERENCES "XX_TANGO"."XX_INT_COMPONENTS_T" ("COMPONENT_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/