--
-- Table "XX_INT_HIERARCHIES_T"
--
CREATE TABLE "XX_TANGO"."XX_INT_HIERARCHIES_T" 
   (	"INT_HIERARCHIE_ID" NUMBER DEFAULT XX_TANGO.XX_INT_HIERARCHIES_S1.nextval, 
	"INT_HIERARCHIE_NUM" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SHORT_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INTEGRATION_ID" NUMBER, 
	"INT_LAYER_ID" NUMBER, 
	"SEQ_NO" NUMBER NOT NULL ENABLE, 
	"ENABLE_FLAG" BOOLEAN NOT NULL ENABLE, 
	"OBJECT_VERSION_NUMBER" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PROCESS_API_MASTER_ID" NUMBER, 
	"SYSYTEM_API_MASTER_ID" NUMBER, 
	 CONSTRAINT "XX_INT_HIERARCHIES_PK1" PRIMARY KEY ("INT_HIERARCHIE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "XX_INT_HIERARCHIES_FK1" FOREIGN KEY ("INTEGRATION_ID")
	  REFERENCES "XX_TANGO"."XX_INTEGRATIONS_T" ("INTEGRATION_ID") ENABLE, 
	 CONSTRAINT "XX_INT_HIERARCHIES_FK2" FOREIGN KEY ("INT_LAYER_ID")
	  REFERENCES "XX_TANGO"."XX_INT_LAYERS_T" ("INT_LAYERS_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/