--
-- Table "XX_INT_PROCESS_MAP_T"
--
CREATE TABLE "XX_TANGO"."XX_INT_PROCESS_MAP_T" 
   (	"INT_PROCESS_MAP_ID" NUMBER DEFAULT XX_TANGO.XX_INT_PROCESS_MAP_S1.nextval, 
	"INT_PROCESS_MAP_NUM" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SHORT_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"L1_PROCESS_ID" NUMBER, 
	"L2_PROCESS_ID" NUMBER, 
	"L3_PROCESS_ID" NUMBER, 
	"L4_PROCESS_ID" NUMBER, 
	"L5_PROCESS_ID" NUMBER, 
	"L6_PROCESS_ID" NUMBER, 
	"L7_PROCESS_ID" NUMBER, 
	"L8_PROCESS_ID" NUMBER, 
	"L9_PROCESS_ID" NUMBER, 
	"INTEGRATION_ID" NUMBER, 
	"SEQ_NO" NUMBER NOT NULL ENABLE, 
	"ENABLE_FLAG" BOOLEAN NOT NULL ENABLE, 
	"OBJECT_VERSION_NUMBER" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_PK1" PRIMARY KEY ("INT_PROCESS_MAP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK1" FOREIGN KEY ("INTEGRATION_ID")
	  REFERENCES "XX_TANGO"."XX_INTEGRATIONS_T" ("INTEGRATION_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK2" FOREIGN KEY ("L1_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK3" FOREIGN KEY ("L2_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK4" FOREIGN KEY ("L3_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK5" FOREIGN KEY ("L4_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK6" FOREIGN KEY ("L5_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK7" FOREIGN KEY ("L6_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK8" FOREIGN KEY ("L7_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK9" FOREIGN KEY ("L8_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE, 
	 CONSTRAINT "XX_INT_PROCESS_MAP_FK10" FOREIGN KEY ("L9_PROCESS_ID")
	  REFERENCES "XX_TANGO"."XX_PROCESS_T" ("PROCESS_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/