--
-- Table "XX_INT_FLOW_T"
--
CREATE TABLE "XX_TANGO"."XX_INT_FLOW_T" 
   (	"INT_FLOW_ID" NUMBER DEFAULT XX_TANGO.XX_INT_FLOW_S1.nextval, 
	"INT_LAYERS_ID" NUMBER, 
	"COMPONENT_ID" NUMBER, 
	"SEQ_NO" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SHORT_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ENABLE_FLAG" BOOLEAN NOT NULL ENABLE, 
	"OBJECT_VERSION_NUMBER" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "INT_FLOWS_PK1" PRIMARY KEY ("INT_FLOW_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "INT_FLOWS_FK1" FOREIGN KEY ("INT_LAYERS_ID")
	  REFERENCES "XX_TANGO"."XX_INT_LAYERS_T" ("INT_LAYERS_ID") ENABLE, 
	 CONSTRAINT "INT_FLOWS_FK2" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES "XX_TANGO"."XX_INT_COMPONENTS_T" ("COMPONENT_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/