--
-- Table "XX_MIDDLEWARES_T"
--
CREATE TABLE "XX_TANGO"."XX_MIDDLEWARES_T" 
   (	"MIDDLEWARE_ID" NUMBER DEFAULT XX_TANGO.XX_MIDDLEWARES_S1.nextval, 
	"NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"SHORT_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"ENVIRONMENT" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PRODUCT" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"APPLICATION" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ENABLE_FLAG" BOOLEAN NOT NULL ENABLE, 
	"OBJECT_VERSION_NUMBER" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"LAST_UPDATE_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "XX_MIDDLEWARES_PK1" PRIMARY KEY ("MIDDLEWARE_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX  ENABLE, 
	 UNIQUE ("SHORT_NAME")
  USING INDEX  ENABLE, 
	 UNIQUE ("DESCRIPTION")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/